### PR TITLE
cfc QSG updates

### PR DESCRIPTION
**Pull request by srweintraub**

### CODE REVIEW

**Comment by srweintraub** [comment]
sorry I snuck in some updates to the LTR quick start guide into this PR as well.

**Comment by srweintraub** [comment]
@cklunch

**Comment by cklunch** [comment]
@srweintraub All looks good, I love the photos of canopy sampling methods. But I think you're also referring to a plot layout figure, and I don't see it in the PR?

**Comment by srweintraub** [comment]
@cklunch right, in the current version of the QSG there is a figure showing plot layout, what I propose is that we replace that (delete it) with the new figure I made. If you agree, I can try to delete the existing figure as part of my PR, I just wanted to check with you first. If you'd like to retain the plot layout diagram instead or in addition, I will ask Dave to help me find an updated one with pointIDs (and possible subplotIDs) labeled.

**Comment by cklunch** [comment]
@srweintraub Aaah, got it. I'm fine with that, I agree the plot layout isn't critical info for CFC.

**Comment by srweintraub** [comment]
@cklunch Great. The one thing is that I didn't delete the old image file from that folder before you accepted this PR, is that OK?

**Comment by cklunch** [comment]
@srweintraub No worries, I'll take care of it.

**Comment by srweintraub** [comment]
@cklunch ok sounds great, thanks. Same for the soils/PLFA pull request, I did not delete the original Figure 1 from the folder even though I uploaded a replacement, so please do that before you knit these again. Cheers!

p.s. I am trying to get two of my labs with new SOPs to get those finalized and submitted by end of this week.

**Pull request merged**
