### PR TITLE
BBC and BRD updates

### PR DESCRIPTION
**Pull request by samsimkin**

### CODE REVIEW

**Comment by cklunch** [comment]
@samsimkin Thanks, looking good! In the bird table join file, can you update the markdown so it includes 4 columns for all rows? Otherwise the code won't parse it correctly. Thanks!

**Comment by samsimkin** [comment]
@cklunch So should I add a pipe delimiter | at the end of all rows and then two pipe delimiters at the end of the rows that have  language about "join not recommended" or "not fully automatable"? The combo of 2 join fields and language about not joining isn't specifically addressed in Writing_instructions_table_joins.md.

**Comment by cklunch** [comment]
@samsimkin Yep, each row should have the same number of pipes. The rows that explain not joining can be empty in the final column, so can end in a double pipe. Thanks!

**Comment by samsimkin** [comment]
@cklunch Cool. I made that change and I think that commit is now included in the pull request.

**Pull request merged**
